server:
  port: 8080
  #Sservlet:
    #context-path: /api
logging:
  level:
    root: info
    com.lrm: debug
  file: logs/my.log

book:
  name: インターネットの世界観
  author: 田中洋一
  isbn: ${random.uuid}
  desctiption: ${book.name},この本は悪くない