
server:
  port: 8080

logging:
  level:
    root: info
    com.ds: debug
  file: logs/debug.log

spring:
  profiles:
    active: dev

  thymeleaf:
    mode: HTML

  datasource:
    # MariaDB
    data-username: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/northwind
    username: root
    password: password
    connectionProperties: useUnicode=true&characterEncoding=UTF-8&serverTimezone=JST


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        # MariaDB
        dialect: org.hibernate.dialect.MariaDBDialect
